### ISSUE TITLE
A command to inspect the parsed AST

### ISSUE THREAD

**Issue by ricardoboss** [ricardoboss/STEP#104]
Something like this (ANTLR):

![](https://raw.githubusercontent.com/antlr/antlr4-tools/master/images/parse-tree.png)

**Comment by chucker** [comment]
https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/get-started/syntax-analysis

Roslyn gives you a side-by-side view, where you can click code and have it highlighted in the tree, and vice versa.

**Comment by ricardoboss** [comment]
I thought of this as a terminal-friendly tree rendered using Spectre.Console. A GUI for any operation should, IMHO, be moved to a seperate project and binary.
