### ISSUE TITLE
More extensive standard framework

### ISSUE THREAD

**Issue by ricardoboss** [ricardoboss/STEP#5]
The goal of this task is to implement more standard functions in the STEP framework.

Currently, there are these functions:

- `print`: prints something to `StdOut`
- `println`: same as `print`, but appends an OS-dependent new line at the end
- `readline`: reads from `StdIn` until a new line is read
- `typename`: returns a string containing the type name of a variable (`number, string, null`, etc)
- `parse`: converts between different built-in types
- `jsonDecode`/`jsonEncode`: de-/encodes STEP types to and from JSON

The language could benefit greatly by providing more functions to manipulate and work with the various data types. Some of these functions include:

# Proposed functions

All proposed functions are categorized into the following categories:

- `mutating`: functions that mutate the given subject
- `pure`: functions that don't mutate the given subject
- `converting`: functions that convert the given subject to another type
- `other`: any functions that do not fit in the other categories

Their category defines the naming of the function:

- `do` prefix for mutating functions
- no prefix for pure functions
- `to` and `from` prefixes for converting functions
- custom prefixes for other functions

## Mutating functions

- [x] #38
	- `doAdd`: Adds the given element to the end of the list.
	- `doRemove`: Removes the first occurrence of the given element from the list.
	- `doPop`: Removes the last element from the list and returns it.
	- `doShift`: Removes the first element from the list and returns it.
	- ~~`doUnshift`: Adds the given element to the front of the list.~~
	- `doRemoveAt`: Removes the element at the given index/key from a list/map.
	- `doInsertAt`: Inserts the given element at the given index in the list.
	- `doSwap`: Swaps the elements at the given indices in a list or the values at the given keys in a map.

## Pure functions

- [x] #32
- [x] #24
- [x] #62
	- `indexOf`: Returns the index/key of the first occurrence of `search` in the given string/list/map.
	- `contains`: Returns `true` if the string/list/map contains the given value.
- [x] #65
	- `startsWith`: Returns `true` if a string starts with the given value.
	- `endsWith`: Returns `true` if a string ends with the given value.
- [x] #67
	- `converted`: Returns a new list with the results of calling the given function on each element in the given list.
	- `filtered`: Returns a new list with all elements in the given list that pass the given predicate.
	- `reversed`: Returns a new list/string with the elements/characters reversed.
	- `sorted`: Sorts the elements in the given list using the given comparison function and returns a new list.
	- `compareTo`: Compares two values and returns a value indicating whether one is less than, equal to or greater than the other.
- [x] #69
	- `sin`, `cos`, `tan`: Returns the sine/cosine/tangent of the given number.
	- `min`, `max`: Returns the minimum/maximum of the given number and value.
	- `clamp`: Returns the given number clamped between the given minimum and maximum.
	- `random`: Returns a random number between the given minimum and maximum.
	- `interpolate`: Returns the linear interpolation of the given minimum and maximum by the given delta.
	- `abs`: Returns the absolute value of the given number.
	- `floor`: Returns the floor of the given number.
	- `ceil`: Returns the ceiling of the given number.
	- `round`: Returns the rounded value of the given number.
	- `sqrt`: Returns the square root of the given number.
	- global variables:
		- `pi`: the ratio of the circumference of a circle to its diameter
		- `e`: natural logarithmic base
- [x] #71
	- `print`: Prints the given subject to `StdOut`.
	- `println`: Prints the given subject to `StdOut` and appends a new line.
	- `readline`: Reads a line from `StdIn` and returns it.
	- `read`: Reads a single character from `StdIn` and returns it.
- [x] #73
- [x] #40

## Converting functions

- [x] #42
- [x] #45
- [x] #49
	- `toJson` (previously `jsonEncode`): Converts the given value to a JSON string.
	- `fromJson` (previously `jsonDecode`): Converts the given JSON string to a STEP type.
	- `toTypeName` (previously `typename`): Returns the type name of the given subject as a string.
- [x] #52
- [x] #54
- [x] #56
- [x] #58

## Other functions

- [x] #36
	- `fileRead`: Reads a file
	- `fileExists`: Checks if the given file exists.
	- `fileDelete`: Deletes the given file.
	- `fileWrite`: Writes a string to a given file.

## Removed functions

- [x] #60

# Documentation

All new functions need documentation.
Each function shall get its own Markdown file in the `StepLang.Wiki\Functions` folder.

It should include a description, a synopsis of the arguments and what is returned.
Any errors or exceptions specific for this function should also be included (or at least references to the error description).

**Comment by chucker** [comment]
> sorts the elements in a list using a comparison function

Does this sort in-place, or return a new sorted list? In the first case, it seems to clash with the behavior of reverse.

(`shift` and `unshift` also strike me as quite… specific for a standard lib.)

> smoothly transitions between two numbers

I don't understand what this means.

> converts a number to a given radix representation (e.g. hex)

How does this actually work? If I pass `16`, does it give me a string?

**Comment by ricardoboss** [comment]
> (shift and unshift also strike me as quite… specific for a standard lib.)

They allow using a list as a stack/queue without adding more data types. The same functionality can be implemented with loops, but I think they are quite useful.

> I don't understand what this means.

`coerce` is not the correct name for what I meant. `interpolate` would be the correct term. The function should take two numbers as bounds and a third to determine where in between the two bounds the result should lie. That is,

- `interpolate(0, 1, 0.5) => 0.5`
- `interpolate(0, 100, 0.3) => 30`
- `interpolate(-50, 50, 0.1) => -40`

> How does this actually work? If I pass 16, does it give me a string?

Yeah, the function only converts to string. Maybe a corresponding `fromRadix` function would also be useful.

**Comment by chucker** [comment]
>They allow using a list as a stack/queue without adding more data types. The same functionality can be implemented with loops, but I think they are quite useful.
>
>coerce is not the correct name for what I meant. interpolate would be the correct term. 

These seem… useful, but quite specific for a beginner's language.

>Yeah, the function only converts to string.

Gotcha.

My overall main concern here — other than how novice/advanced some of these function are — is consistent behavior based on method naming.

My guesses regarding the behavior:

|                       | mutates/in-place | returns different type |
|-----------------------|------------------|------------------------|
| print                 |                  |                        |
| println               |                  |                        |
| readline              |                  |                        |
| typename              |                  | x                      |
| parse                 |                  | x                      |
| jsonDecode/jsonEncode |                  | x                      |
| substring             |                  |                        |
| length                |                  | x                      |
| reverse               |                  |                        |
| indexOf               |                  | x                      |
| contains              |                  | x                      |
| startsWith/endsWith   |                  | x                      |
| length                |                  | x                      |
| reverse               |                  |                        |
| sort                  | x                |                        |
| apply                 |                  |                        |
| contains              |                  | x                      |
| indexOf               |                  | x                      |
| add                   | x                |                        |
| remove                | x                |                        |
| shift                 | x                |                        |
| unshift               | x                |                        |
| removeAt              | x                |                        |
| insertAt              | x                |                        |
| length                |                  | x                      |
| values                |                  | x                      |
| keys                  |                  | x                      |
| contains              |                  | x                      |
| containsKey           |                  | x                      |
| sin/cos/tan           |                  |                        |
| min/max/clamp         |                  |                        |
| coerce                |                  |                        |
| toRadix               |                  | x                      |

In some cases, this seems straightforward to me; in others, I'm not so sure. E.g.:

* if `sort`, `add`, etc. mutate, why doesn't `reverse` mutate?
* perhaps `toRadix` should be `toRadixString` (although that's arguably quite long)

**Comment by ricardoboss** [comment]
Wow, thanks for taking the time to gather all the different classifications! Looks like you guessed everything as I imagined them.

You are correct that its probably easier for new programmers if all methods either mutate the existing value or return a new value, not some mix between them.

I think the default behavior should be that a new value is returned with the requested modification. Obviously types like `map` or `list` are usually modified in place (`sort`, `add`, `removeAt`, etc.).

On the one hand, the language should be self-consistent and not modify with the one function but return a new value with another one, on the other hand, it should prepare and train new programmers to use functions as they appear in other languages. Maybe we should look towards other languages and how they handle these kinds of problems.

**Comment by chucker** [comment]
`length` and `contains` exist for multiple types. Do we

a. have the function itself check the type
b. add a disambiguation mechanism (almost like overloads) a different function is called depending on the input?

**Comment by ricardoboss** [comment]
Technically its easier to have one function and simply check what was passed to it.
Argument count is checked the same way, currently.

Functions are nothing different than a simple variable, that means the first time a functions parameters are checked (count & type) is when it is invoked.

**Comment by ricardoboss** [comment]
I added a `printf` and a `readfile` function.

**Comment by ricardoboss** [comment]
Added a `debugPrint` function
